name: Docker Build and Push

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

env:
  REGISTRY: ${{ secrets.HARBOR_REGISTRY }}
  REGISTRY_GROUP: sigma-livestream
  PRIVATE_APP_IMAGE_TAG: ${{ secrets.HARBOR_REGISTRY }}/sigma-livestream/sigma-streaming-platform-docs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Get Short SHA
        id: get_short_sha
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Login to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.PRIVATE_APP_IMAGE_TAG }}:${{ env.SHORT_SHA }}
          load: true

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.PRIVATE_APP_IMAGE_TAG }}:${{ env.SHORT_SHA }}